// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scqbbwqdxutgewjpsjhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjcWJid3FkeHV0Z2V3anBzamh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NDE1NzIsImV4cCI6MjA3NzMxNzU3Mn0.xULhAZ5AFPJHBMSFizhtWw0RdS9xCnUg_ixv-yILoPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});